spring:
  application:
    name: E-commerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Argentina/Buenos_Aires
    open-in-view: false

server:
  port: 8080