spring:
  application:
    name: E-commerce

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Argentina/Buenos_Aires
    open-in-view: false

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

mercadopago:
  access-token: ${MP_ACCESS_TOKEN}
  notification-url: ${MP_NOTIFICATION_URL:}
  back-url: ${MP_BACK_URL:http://localhost:8080}

correo-argentino:
  base-url: https://apitest.correoargentino.com.ar/micorreo/v1
  user-token: ${CORREO_ARGENTINO_USER_TOKEN:}
  password-token: ${CORREO_ARGENTINO_PASSWORD_TOKEN:}
  customer-id: ${CORREO_ARGENTINO_CUSTOMER_ID:}
  codigo-postal-origen: "1425"

notificaciones:
  remitente: ${MAIL_FROM:no-reply@ecommerce-blandi-arruti.com}
